### ISSUE TITLE
Create Single Event Page

### ISSUE THREAD

**Issue by briceallard** [ShadyBoukhary/Software-Engineering-4143-Project#112]
This page gives single event details, with option to register, date, description, and location details of ONE event.

**Comment by briceallard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Individual Event Page](https://trello.com/c/kb3Rabhb/85-create-individual-event-page)

**Comment by briceallard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Individual Event Presenter](https://trello.com/c/OOZLdsEi/86-create-individual-event-presenter)

**Comment by briceallard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Individual Event Controller](https://trello.com/c/Xsnt60kc/87-create-individual-event-controller)

**Comment by briceallard** [comment]
Submitted for review

**Comment by ShadyBoukhary** [comment]
Merged #113
