### ISSUE TITLE
Example server is not available

### ISSUE THREAD

**Issue by krunduev** [ShadyBoukhary/Software-Engineering-4143-Project#153]
Could not get any response
There is an error making POST to https://45.32.197.143:8000/users.

**Comment by ShadyBoukhary** [comment]
Is this error originating from inside the application?
Please note the protocol is not secure, so no `https`
Post to `http` instead.

**Comment by krunduev** [comment]
http://45.32.197.143:8000/users previously not responded too, but now it works.
May be some network issue.
Thank you for this example!
Wish you successful study and work!
