### ISSUE TITLE
How to run this sample code?

### ISSUE THREAD

**Issue by ccfiel** [ShadyBoukhary/Software-Engineering-4143-Project#154]
try to run this app but got this error.

```
~/Axion-Technologies-HnH$ flutter run
Target file "lib/main.dart" not found.
```

When I tried to look at the code main.dart is inside app folder. 

How to run this sample code?

**Comment by ShadyBoukhary** [comment]
Hi,

Thanks for your interest. You can run `flutter run lib/app/main.dart`.

Alternatively, if you're using vscode, you can change the path in your `launch.json`.

**Comment by ccfiel** [comment]
@ShadyBoukhary Thanks!
