### ISSUE TITLE
Create Login Page View

### ISSUE THREAD

**Issue by ShadyBoukhary** [ShadyBoukhary/Software-Engineering-4143-Project#2]
* Create the Login Page View according to the architecture

**Comment by briceallard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create LoginPage View and Controller](https://trello.com/c/WmYDxiO1/7-create-loginpage-view-and-controller)

**Comment by briceallard** [comment]
The view/UI is pretty much complete. Waiting on Controller ...

**Comment by ShadyBoukhary** [comment]
Close this issue when the UI is merged.

**Comment by briceallard** [comment]
Issue resolved: Login style created.
