### ISSUE TITLE
Set up class to handle user locations within clean architecture

### ISSUE THREAD

**Issue by jeremyglebe** [ShadyBoukhary/Software-Engineering-4143-Project#20]

**Comment by jeremyglebe** [comment]
Trying to figure out the appropriate placement and what data I'm allowed to access under clean architecture. Will be building a skeleton of the class to fit in the architecture and then implementing concretely afterwards.

**Comment by jeremyglebe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Skeleton of class to handle user locations](https://trello.com/c/d0cU546P/12-skeleton-of-class-to-handle-user-locations)

**Comment by ShadyBoukhary** [comment]
@jeremyglebe all user classes and such go in domain

**Comment by jeremyglebe** [comment]
@ShadyBoukhary but getting the location of the user is device, yes?

**Comment by ShadyBoukhary** [comment]
@jeremyglebe yes, but the `Location` class that has `lat` and `lon` for example would be in domain
