### ISSUE TITLE
Create RegisterUsecase

### ISSUE THREAD

**Issue by ShadyBoukhary** [ShadyBoukhary/Software-Engineering-4143-Project#31]

**Comment by ShadyBoukhary** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Register Usecase](https://trello.com/c/VlYQ2gii/18-create-register-usecase)

**Comment by ShadyBoukhary** [comment]
Merged.

**Comment by briceallard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Register Use Case](https://trello.com/c/sf1sWwM7/31-update-register-use-case)

**Comment by briceallard** [comment]
Updated Use Case to include first and last name during registration process.
