### ISSUE TITLE
Implement countdown timer

### ISSUE THREAD

**Issue by briceallard** [ShadyBoukhary/Software-Engineering-4143-Project#54]
Setup a timer that counts down to the event starting date/time

**Comment by briceallard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create CountDown Timer](https://trello.com/c/5Gfd5n7J/36-create-countdown-timer)

**Comment by briceallard** [comment]
Issue resolved.

**Comment by ShadyBoukhary** [comment]
Merged.
