### ISSUE TITLE
TOS Checkbox not working

### ISSUE THREAD

**Issue by briceallard** [ShadyBoukhary/Software-Engineering-4143-Project#58]
Most recent pull request broke the checkbox toggle for the agree to ToS.

**Comment by briceallard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix TOS Checkbox](https://trello.com/c/31phHF27/38-fix-tos-checkbox)

**Comment by briceallard** [comment]
Fixed, awaiting pull request approval.

**Comment by ShadyBoukhary** [comment]
Merged.
