### ISSUE TITLE
Create a listener for gps data

### ISSUE THREAD

**Issue by jeremyglebe** [ShadyBoukhary/Software-Engineering-4143-Project#67]
The current implementation is just a function call. It may be better in some cases to use an ongoing listener for changes in the gps location data.

**Comment by jeremyglebe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create a listener for gps data](https://trello.com/c/OU5d5Wdr/42-create-a-listener-for-gps-data)

**Comment by ShadyBoukhary** [comment]
No longer needed. Implemented in `LocationTrackUseCase`.
Merged in #92
